name: 'üèóÔ∏è Build jellyfin-ffmpeg'

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

on:
  push:
    branches:
      - jellyfin
    paths-ignore:
      - '**/*.md'

  pull_request:
    branches:
      - jellyfin
    paths-ignore:
      - '**/*.md'

jobs:
  build_debian:
    uses: ./.github/workflows/_meta.yaml
    with:
      distro: 'debian'
      codenames: '["bullseye", "bookworm"]'
      architectures: '["amd64", "arm64", "armhf"]'
      release: false

  build_ubuntu:
    uses: ./.github/workflows/_meta.yaml
    with:
      distro: 'ubuntu'
      codenames: '["focal", "jammy", "noble"]'
      architectures: '["amd64", "arm64", "armhf"]'
      release: false

  build_portable_windows:
    uses: ./.github/workflows/_meta_portable.yaml
    with:
      os: 'windows'
      architectures: '["win64"]'
      release: false

  build_portable_windows_clang:
    uses: ./.github/workflows/_meta_win_clang_portable.yaml
    with:
      release: false

  build_portable_linux:
    uses: ./.github/workflows/_meta_portable.yaml
    with:
      os: 'linux'
      architectures: '["amd64", "arm64"]'
      release: false

  build_portable_mac:
    uses: ./.github/workflows/_meta_mac_portable.yaml
    with:
      release: false
